pub struct GameEntry {
    pub id: &'static str,
    pub sel_property: &'static str,
    pub inst_property: &'static str,
    pub size_gib: f32,
    pub display_name_short: &'static str,
    pub exe_indicator: &'static str,
    pub depot1_regex: Option<&'static str>,
    pub depot2_regex: Option<&'static str>,
    pub epic_regex: &'static [&'static str],
}

impl GameEntry {
    pub fn display_name(&self) -> String {
        format!("{} [{:.2} GiB]", self.display_name_short, self.size_gib)
    }
}

pub const GAMES: &[GameEntry] = &[
    GameEntry {
        id: "base",
        sel_property: "sel_base",
        inst_property: "inst_base",
        display_name_short: "Base files",
        size_gib: 0.91,
        exe_indicator: "WaitTitleProject.exe",
        depot1_regex: Some(r"regex:^(Image/SettingMenu\.(hed|pkg)|steam_api64\.dll|WaitTitleProject\.exe)$"),
        depot2_regex: None,
        epic_regex: &[r"regex:^(Image/SettingMenu\.(hed|pkg)|WaitTitleProject\.exe|EOSSDK-Win64-Shipping\.dll)$"],
    },
    GameEntry {
        id: "mare",
        sel_property: "sel_mare",
        inst_property: "inst_mare",
        display_name_short: "Mare (Launcher & movies engine)",
        size_gib: 2.57,
        exe_indicator: "KINGDOM HEARTS HD 1.5+2.5 Launcher.exe",
        depot1_regex: Some(r"regex:^(Image/Mare\.(hed|pkg)|KINGDOM HEARTS HD 1\.5\+2\.5 (Launcher|ReMIX)\.exe)$"),
        depot2_regex: None,
        epic_regex: &[r"regex:^(Image/Mare\.(hed|pkg)|KINGDOM HEARTS HD 1\.5\+2\.5 (Launcher|ReMIX)\.exe)$"],
    },
    GameEntry {
        id: "kh1",
        sel_property: "sel_kh1",
        inst_property: "inst_kh1",
        display_name_short: "Kingdom Hearts Final Mix",
        size_gib: 10.45,
        exe_indicator: "KINGDOM HEARTS FINAL MIX.exe",
        depot1_regex: Some(r"regex:^(Image/dt/kh1_.*\.(hed|pkg)|KINGDOM HEARTS FINAL MIX\.exe)$"),
        depot2_regex: Some(r"regex:^STEAM/dt/KH1Movie/.*$"),
        epic_regex: &[
            r"regex:^(Image/en/kh1_.*\.(hed|pkg)|KINGDOM HEARTS FINAL MIX\.exe)$",
            r"regex:^EPIC/en/KH1Movie/.*$",
        ],
    },
    GameEntry {
        id: "recom",
        sel_property: "sel_recom",
        inst_property: "inst_recom",
        display_name_short: "Kingdom Hearts Re:Chain of Memories",
        size_gib: 8.68,
        exe_indicator: "KINGDOM HEARTS Re_Chain of Memories.exe",
        depot1_regex: Some(r"regex:^(Image/dt/Recom\.(hed|pkg)|KINGDOM HEARTS Re_Chain of Memories\.exe)$"),
        depot2_regex: Some(r"regex:^STEAM/dt/KHCReSource/.*$"),
        epic_regex: &[
            r"regex:^(Image/en/Recom\.(hed|pkg)|KINGDOM HEARTS Re_Chain of Memories\.exe)$",
            r"regex:^EPIC/en/KHCReSource/.*$",
        ],
    },
    GameEntry {
        id: "days",
        sel_property: "sel_days",
        inst_property: "inst_days",
        display_name_short: "Kingdom Hearts 358/2 Days (movie)",
        size_gib: 4.36,
        exe_indicator: "",
        depot1_regex: None,
        depot2_regex: Some(r"regex:^STEAM/Mare/MOVIE/Days/.*$"),
        epic_regex: &[r"regex:^EPIC/Mare/MOVIE/Days/.*$"],
    },
    GameEntry {
        id: "kh2",
        sel_property: "sel_kh2",
        inst_property: "inst_kh2",
        display_name_short: "Kingdom Hearts II Final Mix",
        size_gib: 16.74,
        exe_indicator: "KINGDOM HEARTS II FINAL MIX.exe",
        depot1_regex: Some(r"regex:^(Image/dt/kh2_.*\.(hed|pkg)|KINGDOM HEARTS II FINAL MIX\.exe)$"),
        depot2_regex: Some(r"regex:^STEAM/juefigs/KH2ReSource/.*$"),
        epic_regex: &[
            r"regex:^(Image/en/kh2_.*\.(hed|pkg)|KINGDOM HEARTS II FINAL MIX\.exe)$",
            r"regex:^EPIC/juefigs/KH2ReSource/.*$",
        ],
    },
    GameEntry {
        id: "bbs",
        sel_property: "sel_bbs",
        inst_property: "inst_bbs",
        display_name_short: "Kingdom Hearts Birth by Sleep Final Mix",
        size_gib: 8.21,
        exe_indicator: "KINGDOM HEARTS Birth by Sleep FINAL MIX.exe",
        depot1_regex: Some(r"regex:^(Image/dt/bbs_.*\.(hed|pkg)|KINGDOM HEARTS Birth by Sleep FINAL MIX\.exe)$"),
        depot2_regex: Some(r"regex:^STEAM/juefigs/BBSReSource/.*$"),
        epic_regex: &[
            r"regex:^(Image/en/bbs_.*\.(hed|pkg)|KINGDOM HEARTS Birth by Sleep FINAL MIX\.exe)$",
            r"regex:^EPIC/juefigs/BBSReSource/.*$",
        ],
    },
    GameEntry {
        id: "coded",
        sel_property: "sel_coded",
        inst_property: "inst_coded",
        display_name_short: "Kingdom Hearts Re:coded (movie)",
        size_gib: 3.15,
        exe_indicator: "",
        depot1_regex: None,
        depot2_regex: Some(r"regex:^STEAM/Mare/MOVIE/ReCoded/.*$"),
        epic_regex: &[r"regex:^EPIC/Mare/MOVIE/ReCoded/.*$"],
    },
    GameEntry {
        id: "theater",
        sel_property: "sel_theater",
        inst_property: "inst_theater",
        display_name_short: "Theater (cutscenes as movie)",
        size_gib: 10.35,
        exe_indicator: "KINGDOM HEARTS Theater.exe",
        depot1_regex: Some(r"regex:^(Image/dt/Theater\.(hed|pkg)|KINGDOM HEARTS Theater\.exe)$"),
        depot2_regex: Some(r"regex:^STEAM/Theater/.*$"),
        epic_regex: &[
            r"regex:^(Image/en/Theater\.(hed|pkg)|KINGDOM HEARTS Theater\.exe)$",
            r"regex:^EPIC/Theater/.*$",
        ],
    },
];